blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://github.com/Soundcase/Soundcase/issues
    about: Please use the following link to create a new issue.
  - name: Patreon
    url: https://www.patreon.com/lenoirc
    about: Love Soundcase? Please consider supporting us via Patreon.
  - name: Open Collective
    url: https://opencollective.com/soundcase/donate
    about: Love Soundcase? Please consider supporting us via Open Collective.
